// Generated by scripts/embed-migrations.ts from drizzle/meta/_journal.json. Do not edit.
/// <reference path="../sql.d.ts" />
import m0 from "../../drizzle/0000_extensions.sql" with { type: "text" };
import m1 from "../../drizzle/0001_schema.sql" with { type: "text" };
import m2 from "../../drizzle/0002_jobs.sql" with { type: "text" };
import m3 from "../../drizzle/0003_audit.sql" with { type: "text" };
import m4 from "../../drizzle/0004_runners_supervisor.sql" with { type: "text" };
import m5 from "../../drizzle/0005_projects_setup.sql" with { type: "text" };
import m6 from "../../drizzle/0006_sessions.sql" with { type: "text" };
import m7 from "../../drizzle/0007_sessions_fork.sql" with { type: "text" };
import m8 from "../../drizzle/0008_sessions_inline.sql" with { type: "text" };
import m9 from "../../drizzle/0009_brains.sql" with { type: "text" };
import m10 from "../../drizzle/0010_connections.sql" with { type: "text" };
import m11 from "../../drizzle/0011_mcp_servers.sql" with { type: "text" };
import m12 from "../../drizzle/0012_preview_share_runner_optional.sql" with { type: "text" };
import m13 from "../../drizzle/0013_message_edits.sql" with { type: "text" };
import m14 from "../../drizzle/0014_push_subscriptions.sql" with { type: "text" };
import m15 from "../../drizzle/0015_messages_blocks_index.sql" with { type: "text" };
import m16 from "../../drizzle/0016_bots.sql" with { type: "text" };
import m17 from "../../drizzle/0017_bot_chains.sql" with { type: "text" };
import m18 from "../../drizzle/0018_inbox_items.sql" with { type: "text" };
import m19 from "../../drizzle/0019_policy_yaml.sql" with { type: "text" };
import m20 from "../../drizzle/0020_policies_yaml.sql" with { type: "text" };
import m21 from "../../drizzle/0021_repo_index.sql" with { type: "text" };
import m22 from "../../drizzle/0022_session_reasoning.sql" with { type: "text" };
import m23 from "../../drizzle/0023_bot_tokens.sql" with { type: "text" };
import m24 from "../../drizzle/0024_spec_bots.sql" with { type: "text" };
import m25 from "../../drizzle/0025_code_bots.sql" with { type: "text" };
import m26 from "../../drizzle/0026_webhooks.sql" with { type: "text" };
import m27 from "../../drizzle/0027_job_timezone.sql" with { type: "text" };
import m28 from "../../drizzle/0028_bot_mcp.sql" with { type: "text" };
import m29 from "../../drizzle/0029_agent_bots.sql" with { type: "text" };
import m30 from "../../drizzle/0030_work_items.sql" with { type: "text" };
import m31 from "../../drizzle/0031_merge_queue.sql" with { type: "text" };
import m32 from "../../drizzle/0032_races.sql" with { type: "text" };
import m33 from "../../drizzle/0033_background_card.sql" with { type: "text" };
import m34 from "../../drizzle/0034_fix_attempts.sql" with { type: "text" };
import m35 from "../../drizzle/0035_runner_local_mcp_servers.sql" with { type: "text" };
import m36 from "../../drizzle/0036_work_views_and_relations.sql" with { type: "text" };
import m37 from "../../drizzle/0037_virtual_keys_and_usage.sql" with { type: "text" };
import m38 from "../../drizzle/0038_budgets.sql" with { type: "text" };
import m39 from "../../drizzle/0039_project_template_source.sql" with { type: "text" };
import m40 from "../../drizzle/0040_policies_unique.sql" with { type: "text" };

export type MigrationSource = {
  idx: number;
  tag: string;
  when: number;
  breakpoints: boolean;
  sql: string;
};

export const migrationSources: MigrationSource[] = [
  { idx: 0, tag: "0000_extensions", when: 1789266672081, breakpoints: true, sql: m0 },
  { idx: 1, tag: "0001_schema", when: 1789266672662, breakpoints: true, sql: m1 },
  { idx: 2, tag: "0002_jobs", when: 1789267095448, breakpoints: true, sql: m2 },
  { idx: 3, tag: "0003_audit", when: 1789269331990, breakpoints: true, sql: m3 },
  { idx: 4, tag: "0004_runners_supervisor", when: 1789375711087, breakpoints: true, sql: m4 },
  { idx: 5, tag: "0005_projects_setup", when: 1789378197025, breakpoints: true, sql: m5 },
  { idx: 6, tag: "0006_sessions", when: 1789397220860, breakpoints: true, sql: m6 },
  { idx: 7, tag: "0007_sessions_fork", when: 1789413619016, breakpoints: true, sql: m7 },
  { idx: 8, tag: "0008_sessions_inline", when: 1789429531454, breakpoints: true, sql: m8 },
  { idx: 9, tag: "0009_brains", when: 1789432725675, breakpoints: true, sql: m9 },
  { idx: 10, tag: "0010_connections", when: 1789434419436, breakpoints: true, sql: m10 },
  { idx: 11, tag: "0011_mcp_servers", when: 1789436757734, breakpoints: true, sql: m11 },
  {
    idx: 12,
    tag: "0012_preview_share_runner_optional",
    when: 1789438762897,
    breakpoints: true,
    sql: m12,
  },
  { idx: 13, tag: "0013_message_edits", when: 1789450387581, breakpoints: true, sql: m13 },
  { idx: 14, tag: "0014_push_subscriptions", when: 1789454375029, breakpoints: true, sql: m14 },
  { idx: 15, tag: "0015_messages_blocks_index", when: 1789456953088, breakpoints: true, sql: m15 },
  { idx: 16, tag: "0016_bots", when: 1789478158989, breakpoints: true, sql: m16 },
  { idx: 17, tag: "0017_bot_chains", when: 1789484479724, breakpoints: true, sql: m17 },
  { idx: 18, tag: "0018_inbox_items", when: 1789489075432, breakpoints: true, sql: m18 },
  { idx: 19, tag: "0019_policy_yaml", when: 1789491123072, breakpoints: true, sql: m19 },
  { idx: 20, tag: "0020_policies_yaml", when: 1789492946369, breakpoints: true, sql: m20 },
  { idx: 21, tag: "0021_repo_index", when: 1789507940175, breakpoints: true, sql: m21 },
  { idx: 22, tag: "0022_session_reasoning", when: 1789519790515, breakpoints: true, sql: m22 },
  { idx: 23, tag: "0023_bot_tokens", when: 1789521616411, breakpoints: true, sql: m23 },
  { idx: 24, tag: "0024_spec_bots", when: 1789529692495, breakpoints: true, sql: m24 },
  { idx: 25, tag: "0025_code_bots", when: 1789531254847, breakpoints: true, sql: m25 },
  { idx: 26, tag: "0026_webhooks", when: 1789533435313, breakpoints: true, sql: m26 },
  { idx: 27, tag: "0027_job_timezone", when: 1789537358518, breakpoints: true, sql: m27 },
  { idx: 28, tag: "0028_bot_mcp", when: 1789538828212, breakpoints: true, sql: m28 },
  { idx: 29, tag: "0029_agent_bots", when: 1789540488390, breakpoints: true, sql: m29 },
  { idx: 30, tag: "0030_work_items", when: 1789550060158, breakpoints: true, sql: m30 },
  { idx: 31, tag: "0031_merge_queue", when: 1789552974684, breakpoints: true, sql: m31 },
  { idx: 32, tag: "0032_races", when: 1789555816533, breakpoints: true, sql: m32 },
  { idx: 33, tag: "0033_background_card", when: 1789557256190, breakpoints: true, sql: m33 },
  { idx: 34, tag: "0034_fix_attempts", when: 1789558398270, breakpoints: true, sql: m34 },
  {
    idx: 35,
    tag: "0035_runner_local_mcp_servers",
    when: 1789580646907,
    breakpoints: true,
    sql: m35,
  },
  {
    idx: 36,
    tag: "0036_work_views_and_relations",
    when: 1789585602551,
    breakpoints: true,
    sql: m36,
  },
  { idx: 37, tag: "0037_virtual_keys_and_usage", when: 1789589609137, breakpoints: true, sql: m37 },
  { idx: 38, tag: "0038_budgets", when: 1789591600197, breakpoints: true, sql: m38 },
  {
    idx: 39,
    tag: "0039_project_template_source",
    when: 1789604291080,
    breakpoints: true,
    sql: m39,
  },
  { idx: 40, tag: "0040_policies_unique", when: 1790290113585, breakpoints: true, sql: m40 },
];
