// Generated by scripts/embed-migrations.ts from drizzle/meta/_journal.json. Do not edit.
import m0 from "../../drizzle/0000_extensions.sql" with { type: "text" };
import m1 from "../../drizzle/0001_schema.sql" with { type: "text" };

export type MigrationSource = {
  idx: number;
  tag: string;
  when: number;
  breakpoints: boolean;
  sql: string;
};

export const migrationSources: MigrationSource[] = [
  { idx: 0, tag: "0000_extensions", when: 1789266672081, breakpoints: true, sql: m0 },
  { idx: 1, tag: "0001_schema", when: 1789266672662, breakpoints: true, sql: m1 },
];
