# Generated by scripts/packaging.ts for v0.3.0 — do not edit by hand.
{
  description = "Perch — self-hosted agentic workspace";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = { self, nixpkgs }:
    let
      systems = {
        "x86_64-linux" = { asset = "perch-linux-x64"; sha256 = "efc2dbe3c14719b2bf795b87c069ea5313daf3c419e0180d2258de5412ceddee"; };
        "aarch64-linux" = { asset = "perch-linux-arm64"; sha256 = "fd75d6f224b22bb4d8920880828cf86fc74f3ef93a495d79da8626cd55aaa76c"; };
        "x86_64-darwin" = { asset = "perch-darwin-x64"; sha256 = "61c7312e3ee938aaefc00ad5e2bab1435fee6bce9e0058d0a4fd2031df106eae"; };
        "aarch64-darwin" = { asset = "perch-darwin-arm64"; sha256 = "dc943018ca47dfcdb62c31b900de48b22d710864e7537755221de629385f695c"; };
      };
      forAll = f: nixpkgs.lib.genAttrs (builtins.attrNames systems) f;
    in {
      packages = forAll (system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          here = systems.${system};
        in {
          default = pkgs.stdenvNoCC.mkDerivation {
            pname = "perch";
            version = "0.3.0";
            src = pkgs.fetchurl {
              url = "https://github.com/12burb/perch/releases/download/v0.3.0/${here.asset}";
              sha256 = here.sha256;
            };
            dontUnpack = true;
            installPhase = "install -Dm755 $src $out/bin/perch";
          };
        });
    };
}
