// Migration SQL files are imported as text (Bun `with { type: "text" }`), which embeds them into the
// compiled laptop binary. Generated by scripts/embed-migrations.ts.
declare module "*.sql" {
  const contents: string;
  export default contents;
}
