/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppWorkspaceRouteImport } from './routes/_app/$workspace'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppWorkspaceModeRouteImport } from './routes/_app/$workspace/$mode'
import { Route as AppWorkspaceEnvironmentsRouteImport } from './routes/_app/$workspace/environments'
import { Route as AppWorkspaceSettingsRouteImport } from './routes/_app/$workspace/settings'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppWorkspaceCodeProjectRouteImport } from './routes/_app/$workspace/code.$project'
import { Route as AppWorkspaceHomeChannelRouteImport } from './routes/_app/$workspace/home.$channel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceModeRoute = AppWorkspaceModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceEnvironmentsRoute =
  AppWorkspaceEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceSettingsRoute = AppWorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceCodeProjectRoute = AppWorkspaceCodeProjectRouteImport.update({
  id: '/code/$project',
  path: '/code/$project',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceHomeChannelRoute = AppWorkspaceHomeChannelRouteImport.update({
  id: '/home/$channel',
  path: '/home/$channel',
  getParentRoute: () => AppWorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$workspace': typeof AppWorkspaceRouteWithChildren
  '/welcome': typeof AppWelcomeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$workspace/$mode': typeof AppWorkspaceModeRoute
  '/$workspace/environments': typeof AppWorkspaceEnvironmentsRoute
  '/$workspace/settings': typeof AppWorkspaceSettingsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/$workspace/code/$project': typeof AppWorkspaceCodeProjectRoute
  '/$workspace/home/$channel': typeof AppWorkspaceHomeChannelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$workspace': typeof AppWorkspaceRouteWithChildren
  '/welcome': typeof AppWelcomeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$workspace/$mode': typeof AppWorkspaceModeRoute
  '/$workspace/environments': typeof AppWorkspaceEnvironmentsRoute
  '/$workspace/settings': typeof AppWorkspaceSettingsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/$workspace/code/$project': typeof AppWorkspaceCodeProjectRoute
  '/$workspace/home/$channel': typeof AppWorkspaceHomeChannelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/$workspace': typeof AppWorkspaceRouteWithChildren
  '/_app/welcome': typeof AppWelcomeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/$workspace/$mode': typeof AppWorkspaceModeRoute
  '/_app/$workspace/environments': typeof AppWorkspaceEnvironmentsRoute
  '/_app/$workspace/settings': typeof AppWorkspaceSettingsRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/$workspace/code/$project': typeof AppWorkspaceCodeProjectRoute
  '/_app/$workspace/home/$channel': typeof AppWorkspaceHomeChannelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/$workspace'
    | '/welcome'
    | '/invite/$token'
    | '/$workspace/$mode'
    | '/$workspace/environments'
    | '/$workspace/settings'
    | '/settings/profile'
    | '/settings/security'
    | '/$workspace/code/$project'
    | '/$workspace/home/$channel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/$workspace'
    | '/welcome'
    | '/invite/$token'
    | '/$workspace/$mode'
    | '/$workspace/environments'
    | '/$workspace/settings'
    | '/settings/profile'
    | '/settings/security'
    | '/$workspace/code/$project'
    | '/$workspace/home/$channel'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/_app/$workspace'
    | '/_app/welcome'
    | '/invite/$token'
    | '/_app/$workspace/$mode'
    | '/_app/$workspace/environments'
    | '/_app/$workspace/settings'
    | '/_app/settings/profile'
    | '/_app/settings/security'
    | '/_app/$workspace/code/$project'
    | '/_app/$workspace/home/$channel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspace': {
      id: '/_app/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspace/$mode': {
      id: '/_app/$workspace/$mode'
      path: '/$mode'
      fullPath: '/$workspace/$mode'
      preLoaderRoute: typeof AppWorkspaceModeRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/$workspace/environments': {
      id: '/_app/$workspace/environments'
      path: '/environments'
      fullPath: '/$workspace/environments'
      preLoaderRoute: typeof AppWorkspaceEnvironmentsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/$workspace/settings': {
      id: '/_app/$workspace/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof AppWorkspaceSettingsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$workspace/code/$project': {
      id: '/_app/$workspace/code/$project'
      path: '/code/$project'
      fullPath: '/$workspace/code/$project'
      preLoaderRoute: typeof AppWorkspaceCodeProjectRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/$workspace/home/$channel': {
      id: '/_app/$workspace/home/$channel'
      path: '/home/$channel'
      fullPath: '/$workspace/home/$channel'
      preLoaderRoute: typeof AppWorkspaceHomeChannelRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
  }
}

interface AppWorkspaceRouteChildren {
  AppWorkspaceModeRoute: typeof AppWorkspaceModeRoute
  AppWorkspaceEnvironmentsRoute: typeof AppWorkspaceEnvironmentsRoute
  AppWorkspaceSettingsRoute: typeof AppWorkspaceSettingsRoute
  AppWorkspaceCodeProjectRoute: typeof AppWorkspaceCodeProjectRoute
  AppWorkspaceHomeChannelRoute: typeof AppWorkspaceHomeChannelRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceModeRoute: AppWorkspaceModeRoute,
  AppWorkspaceEnvironmentsRoute: AppWorkspaceEnvironmentsRoute,
  AppWorkspaceSettingsRoute: AppWorkspaceSettingsRoute,
  AppWorkspaceCodeProjectRoute: AppWorkspaceCodeProjectRoute,
  AppWorkspaceHomeChannelRoute: AppWorkspaceHomeChannelRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppWelcomeRoute: AppWelcomeRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
