# Generated by scripts/packaging.ts for v0.3.0 — do not edit by hand.
class Perch < Formula
  desc "Self-hosted agentic workspace: IDE, team chat, bots, connections, model gateway"
  homepage "https://github.com/12burb/perch"
  version "0.3.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/12burb/perch/releases/download/v0.3.0/perch-darwin-arm64"
      sha256 "dc943018ca47dfcdb62c31b900de48b22d710864e7537755221de629385f695c"
    else
      url "https://github.com/12burb/perch/releases/download/v0.3.0/perch-darwin-x64"
      sha256 "61c7312e3ee938aaefc00ad5e2bab1435fee6bce9e0058d0a4fd2031df106eae"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/12burb/perch/releases/download/v0.3.0/perch-linux-arm64"
      sha256 "fd75d6f224b22bb4d8920880828cf86fc74f3ef93a495d79da8626cd55aaa76c"
    else
      url "https://github.com/12burb/perch/releases/download/v0.3.0/perch-linux-x64"
      sha256 "efc2dbe3c14719b2bf795b87c069ea5313daf3c419e0180d2258de5412ceddee"
    end
  end

  def install
    bin.install Dir["perch-*"].first => "perch"
  end

  test do
    assert_match "perch", shell_output("#{bin}/perch help")
  end
end
