#!/usr/bin/env bun
/**
 * Builds the perch binaries and the `perch-dev` npm package (spec §2, §8 "perch binaries per
 * platform", "npm publish of the perch package"). Needs a web build first.
 *
 *   bun scripts/build-cli.ts [--targets bun-linux-x64,…] [--out dist/cli] [--version 1.2.3] [--no-compile]
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { parseArgs } from "node:util";

export const TARGETS = [
  "bun-linux-x64",
  "bun-linux-arm64",
  "bun-darwin-arm64",
  "bun-darwin-x64",
  "bun-windows-x64",
] as const;

const root = resolve(import.meta.dir, "..");
const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    targets: { type: "string" },
    out: { type: "string" },
    version: { type: "string" },
    "no-compile": { type: "boolean" },
    "no-npm": { type: "boolean" },
  },
  strict: true,
});

const dist = join(root, "apps", "web", "dist");
if (!existsSync(join(dist, "index.html"))) {
  console.error("no web build; run bun run --filter @perch/web build first");
  process.exit(1);
}
const out = resolve(values.out ?? join(root, "dist", "cli"));
mkdirSync(out, { recursive: true });
const cliPkg = JSON.parse(readFileSync(join(root, "apps", "cli", "package.json"), "utf8")) as {
  version: string;
};
const version = values.version ?? cliPkg.version;

function run(cmd: string[], cwd = root): void {
  const proc = Bun.spawnSync(cmd, { cwd, stdout: "inherit", stderr: "inherit" });
  if (proc.exitCode !== 0) throw new Error(`${cmd.join(" ")} exited with ${proc.exitCode}`);
}

const placeholder =
  "// Generated by scripts/embed-web.ts from apps/web/dist. Do not edit; the committed version is empty.\n\nexport const webAssets: Record<string, string> = {};\n";
const genFile = join(root, "apps", "cli", "src", "web-assets.gen.ts");
// Start from the placeholder whatever an earlier run left behind.
writeFileSync(genFile, placeholder);

try {
  // 1. The npm package first, with the placeholder (an empty asset map): a bundled script that runs on
  //    an installed Bun with the web app copied beside it (webDistDir() finds ./web).
  if (!values["no-npm"]) {
    const npmDir = join(out, "npm");
    rmSync(npmDir, { recursive: true, force: true });
    mkdirSync(npmDir, { recursive: true });
    // --outdir: the PGlite runtime files (wasm, data, tarballs) are emitted beside the script.
    run([
      "bun",
      "build",
      "--target=bun",
      // The same version the binaries get: `npx perch-dev version` says it, and `perch upgrade
      // --check` compares against it rather than against "dev".
      "--define",
      `process.env.PERCH_VERSION=${JSON.stringify(version)}`,
      "apps/cli/src/index.ts",
      "--outdir",
      npmDir,
      "--entry-naming",
      "perch.[ext]",
      "--asset-naming",
      "[name]-[hash].[ext]",
    ]);
    cpSync(dist, join(npmDir, "web"), { recursive: true });
    writeFileSync(
      join(npmDir, "package.json"),
      `${JSON.stringify(
        {
          name: "perch-dev",
          version,
          description:
            "Perch: a self-hosted agentic workspace. perch dev runs it on your laptop (needs Bun).",
          license: "AGPL-3.0-only",
          repository: { type: "git", url: "https://github.com/12burb/perch.git" },
          homepage: "https://github.com/12burb/perch",
          bin: { perch: "./perch.js" },
          engines: { bun: ">=1.3.11" },
          files: ["*.js", "*.wasm", "*.data", "*.tar.gz", "web", "README.md"],
        },
        null,
        2,
      )}\n`,
    );
    cpSync(join(root, "apps", "cli", "README.md"), join(npmDir, "README.md"));
    console.log(`npm package staged in ${npmDir}`);
  }

  // 2. Embed the web app and compile one binary per target.
  run(["bun", "scripts/embed-web.ts"]);
  if (!values["no-compile"]) {
    const targets = (values.targets?.split(",") ?? [...TARGETS])
      .map((t) => t.trim())
      .filter(Boolean);
    for (const target of targets) {
      const suffix = target.replace(/^bun-/, "");
      const outfile = join(out, `perch-${suffix}${target.includes("windows") ? ".exe" : ""}`);
      console.log(`compiling ${target} → ${outfile}`);
      run([
        "bun",
        "build",
        "--compile",
        `--target=${target}`,
        "--define",
        `process.env.PERCH_VERSION=${JSON.stringify(version)}`,
        "apps/cli/src/index.ts",
        "--outfile",
        outfile,
      ]);
    }
  }
} finally {
  // 3. Leave the committed placeholder in place.
  writeFileSync(genFile, placeholder);
}
