#!/usr/bin/env bun
/**
 * Builds the Perch desktop app for the platform this runs on (ADR-0063). The native webview addon is
 * installed per platform, so unlike build-cli.ts there is no cross-compilation: the release workflow
 * runs this on one runner per platform. Needs a web build first.
 *
 *   bun scripts/build-desktop.ts [--out dist/desktop] [--version 1.2.3]
 *
 * Writes perch-desktop-<os>-<arch>[.exe] (Windows: icon, product metadata, no console window), on
 * macOS also Perch.app and Perch-macos-<arch>.app.zip, and BINARY (the binary's file name) for scripts.
 */
import {
  chmodSync,
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { parseArgs } from "node:util";

const root = resolve(import.meta.dir, "..");
const { values } = parseArgs({
  args: process.argv.slice(2),
  options: { out: { type: "string" }, version: { type: "string" } },
  strict: true,
});

const dist = join(root, "apps", "web", "dist");
if (!existsSync(join(dist, "index.html"))) {
  console.error("no web build; run bun run --filter @perch/web build first");
  process.exit(1);
}
const out = resolve(values.out ?? join(root, "dist", "desktop"));
mkdirSync(out, { recursive: true });
const pkg = JSON.parse(readFileSync(join(root, "apps", "desktop", "package.json"), "utf8")) as {
  version: string;
};
const version = values.version ?? pkg.version;
const platform = process.platform === "win32" ? "windows" : process.platform;
const binary = `perch-desktop-${platform}-${process.arch}${platform === "windows" ? ".exe" : ""}`;
const assets = join(root, "apps", "desktop", "assets");

function run(cmd: string[], cwd = root): void {
  const proc = Bun.spawnSync(cmd, { cwd, stdout: "inherit", stderr: "inherit" });
  if (proc.exitCode !== 0) throw new Error(`${cmd.join(" ")} exited with ${proc.exitCode}`);
}

/** Windows wants a numeric x.y.z.w; a pre-release suffix is dropped. */
function windowsVersion(v: string): string {
  const parts = v
    .replace(/[-+].*$/, "")
    .split(".")
    .map((p) => Number.parseInt(p, 10) || 0);
  while (parts.length < 4) parts.push(0);
  return parts.slice(0, 4).join(".");
}

const placeholder =
  "// Generated by scripts/embed-web.ts from apps/web/dist. Do not edit; the committed version is empty.\n\nexport const webAssets: Record<string, string> = {};\n";
const genFile = join(root, "apps", "cli", "src", "web-assets.gen.ts");
writeFileSync(genFile, placeholder);

try {
  run(["bun", "scripts/embed-web.ts"]);
  const outfile = join(out, binary);
  console.log(`compiling the desktop app → ${outfile}`);
  run([
    "bun",
    "build",
    "--compile",
    "--define",
    `process.env.PERCH_VERSION=${JSON.stringify(version)}`,
    ...(platform === "windows"
      ? [
          "--windows-hide-console",
          `--windows-icon=${join(assets, "icon.ico")}`,
          "--windows-title=Perch",
          "--windows-publisher=Perch contributors",
          `--windows-version=${windowsVersion(version)}`,
          "--windows-description=Perch desktop app",
          "--windows-copyright=AGPL-3.0-only",
        ]
      : []),
    // The worker threads are extra entrypoints, embedded as server-worker.js and closer-worker.js.
    "apps/desktop/src/index.ts",
    "apps/desktop/src/server-worker.ts",
    "apps/desktop/src/closer-worker.ts",
    "--outfile",
    outfile,
  ]);
  writeFileSync(join(out, "BINARY"), `${binary}\n`);

  if (platform === "darwin") {
    // An .app bundle: Finder, the Dock, and Launchpad need it; the binary alone still works from a
    // terminal. Unsigned (docs/desktop.md explains the first launch).
    const app = join(out, "Perch.app");
    rmSync(app, { recursive: true, force: true });
    mkdirSync(join(app, "Contents", "MacOS"), { recursive: true });
    mkdirSync(join(app, "Contents", "Resources"), { recursive: true });
    cpSync(outfile, join(app, "Contents", "MacOS", "perch-desktop"));
    chmodSync(join(app, "Contents", "MacOS", "perch-desktop"), 0o755);
    cpSync(join(assets, "icon.icns"), join(app, "Contents", "Resources", "Perch.icns"));
    writeFileSync(
      join(app, "Contents", "Info.plist"),
      `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Perch</string>
  <key>CFBundleDisplayName</key><string>Perch</string>
  <key>CFBundleIdentifier</key><string>dev.perch.desktop</string>
  <key>CFBundleVersion</key><string>${version}</string>
  <key>CFBundleShortVersionString</key><string>${version}</string>
  <key>CFBundleExecutable</key><string>perch-desktop</string>
  <key>CFBundleIconFile</key><string>Perch</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>10.15</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSApplicationCategoryType</key><string>public.app-category.developer-tools</string>
</dict>
</plist>
`,
    );
    const zip = join(out, `Perch-macos-${process.arch}.app.zip`);
    rmSync(zip, { force: true });
    // ditto keeps the executable bit and the bundle layout intact.
    run(["ditto", "-c", "-k", "--keepParent", app, zip], out);
    console.log(`bundled ${app} → ${zip}`);
  }
} finally {
  writeFileSync(genFile, placeholder);
}
