#!/usr/bin/env bun
/**
 * Generates apps/cli/src/web-assets.gen.ts: one `with { type: "file" }` import per file in apps/web/dist
 * (source maps excluded), so `bun build --compile` embeds the web app into the perch binary and
 * `perch dev` serves it without a dist directory (ADR-0060). The committed placeholder exports an
 * empty map; the release workflow runs this before compiling.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const dist = resolve(process.argv[2] ?? join(root, "apps", "web", "dist"));
const out = join(root, "apps", "cli", "src", "web-assets.gen.ts");

function walk(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir).sort()) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) files.push(...walk(path));
    else if (!entry.endsWith(".map")) files.push(path);
  }
  return files;
}

const files = walk(dist);
const imports = files
  .map(
    (file, i) =>
      `import a${i} from "${relative(join(root, "apps", "cli", "src"), file).replace(/\\/g, "/")}" with { type: "file" };`,
  )
  .join("\n");
const entries = files
  .map((file, i) => `  ${JSON.stringify(`/${relative(dist, file).replace(/\\/g, "/")}`)}: a${i},`)
  .join("\n");
writeFileSync(
  out,
  `// Generated by scripts/embed-web.ts from apps/web/dist. Do not edit; the committed version is empty.
${imports}

export const webAssets: Record<string, string> = {
${entries}
};
`,
);
console.log(`embedded ${files.length} files into ${out}`);
