/**
 * The package-manager manifests for a release (task 4.3).
 *
 * Homebrew, winget, the AUR and nix all want the same three facts — a version, a URL, and a
 * checksum — written four different ways. They are generated from the release's own `SHA256SUMS`
 * rather than typed, because a packaging file with a stale checksum is an install that fails for
 * somebody else on a Sunday.
 *
 *   bun scripts/packaging.ts --version v0.2.0 --sums dist/cli/SHA256SUMS --out dist/packaging
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { parseArgs } from "node:util";

export const REPO = "12burb/perch";

export type Sums = Record<string, string>;

/** `<sha256>  <name>` per line, the way `sha256sum` writes it. */
export function parseSums(text: string): Sums {
  const sums: Sums = {};
  for (const line of text.split("\n")) {
    const match = /^([0-9a-f]{64})\s+\*?(.+?)\s*$/i.exec(line.trim());
    if (match?.[1] && match[2]) sums[match[2]] = match[1].toLowerCase();
  }
  return sums;
}

function need(sums: Sums, name: string): string {
  const sum = sums[name];
  if (!sum) throw new Error(`SHA256SUMS has no line for ${name}`);
  return sum;
}

/** `v0.2.0` → `0.2.0`, because every packaging format wants the bare number. */
export function bare(version: string): string {
  return version.replace(/^v/, "");
}

function url(version: string, asset: string, repo = REPO): string {
  return `https://github.com/${repo}/releases/download/${version}/${asset}`;
}

/** A Homebrew formula, for `brew install 12burb/perch/perch`. */
export function homebrew(version: string, sums: Sums, repo = REPO): string {
  const number = bare(version);
  return `# Generated by scripts/packaging.ts for ${version} — do not edit by hand.
class Perch < Formula
  desc "Self-hosted agentic workspace: IDE, team chat, bots, connections, model gateway"
  homepage "https://github.com/${repo}"
  version "${number}"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "${url(version, "perch-darwin-arm64", repo)}"
      sha256 "${need(sums, "perch-darwin-arm64")}"
    else
      url "${url(version, "perch-darwin-x64", repo)}"
      sha256 "${need(sums, "perch-darwin-x64")}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${url(version, "perch-linux-arm64", repo)}"
      sha256 "${need(sums, "perch-linux-arm64")}"
    else
      url "${url(version, "perch-linux-x64", repo)}"
      sha256 "${need(sums, "perch-linux-x64")}"
    end
  end

  def install
    bin.install Dir["perch-*"].first => "perch"
  end

  test do
    assert_match "perch", shell_output("#{bin}/perch help")
  end
end
`;
}

/** The three files winget wants, keyed by the name each one is published under. */
export function winget(version: string, sums: Sums, repo = REPO): Record<string, string> {
  const number = bare(version);
  const id = "Perch.Perch";
  // Every scalar is quoted: an unquoted `1.0` is a float to a YAML reader, an unquoted checksum of
  // all digits is a number, and the description has a colon in it.
  return {
    [`${id}.yaml`]: `# Generated by scripts/packaging.ts for ${version} — do not edit by hand.
PackageIdentifier: "${id}"
PackageVersion: "${number}"
DefaultLocale: "en-US"
ManifestType: version
ManifestVersion: "1.6.0"
`,
    [`${id}.installer.yaml`]: `PackageIdentifier: "${id}"
PackageVersion: "${number}"
InstallerType: portable
Commands:
  - perch
Installers:
  - Architecture: x64
    InstallerUrl: "${url(version, "perch-windows-x64.exe", repo)}"
    InstallerSha256: "${need(sums, "perch-windows-x64.exe").toUpperCase()}"
ManifestType: installer
ManifestVersion: "1.6.0"
`,
    [`${id}.locale.en-US.yaml`]: `PackageIdentifier: "${id}"
PackageVersion: "${number}"
PackageLocale: "en-US"
Publisher: "Perch"
PackageName: "Perch"
License: "AGPL-3.0-or-later"
ShortDescription: "Self-hosted agentic workspace: IDE, team chat, bots, connections, model gateway"
PackageUrl: "https://github.com/${repo}"
ManifestType: defaultLocale
ManifestVersion: "1.6.0"
`,
  };
}

/** An AUR PKGBUILD for `perch-bin`. */
export function pkgbuild(version: string, sums: Sums, repo = REPO): string {
  const number = bare(version);
  return `# Generated by scripts/packaging.ts for ${version} — do not edit by hand.
# Maintainer: Perch <noreply@github.com>
pkgname=perch-bin
pkgver=${number}
pkgrel=1
pkgdesc="Self-hosted agentic workspace: IDE, team chat, bots, connections, model gateway"
arch=('x86_64' 'aarch64')
url="https://github.com/${repo}"
license=('AGPL-3.0-or-later')
provides=('perch')
conflicts=('perch')
source_x86_64=("perch-\${pkgver}-x86_64::${url(version, "perch-linux-x64", repo)}")
source_aarch64=("perch-\${pkgver}-aarch64::${url(version, "perch-linux-arm64", repo)}")
sha256sums_x86_64=('${need(sums, "perch-linux-x64")}')
sha256sums_aarch64=('${need(sums, "perch-linux-arm64")}')

package() {
  install -Dm755 "\${srcdir}/perch-\${pkgver}-\${CARCH}" "\${pkgdir}/usr/bin/perch"
}
`;
}

/** A flake that builds nothing and installs the release binary. */
export function flake(version: string, sums: Sums, repo = REPO): string {
  const number = bare(version);
  return `# Generated by scripts/packaging.ts for ${version} — do not edit by hand.
{
  description = "Perch — self-hosted agentic workspace";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = { self, nixpkgs }:
    let
      systems = {
        "x86_64-linux" = { asset = "perch-linux-x64"; sha256 = "${need(sums, "perch-linux-x64")}"; };
        "aarch64-linux" = { asset = "perch-linux-arm64"; sha256 = "${need(sums, "perch-linux-arm64")}"; };
        "x86_64-darwin" = { asset = "perch-darwin-x64"; sha256 = "${need(sums, "perch-darwin-x64")}"; };
        "aarch64-darwin" = { asset = "perch-darwin-arm64"; sha256 = "${need(sums, "perch-darwin-arm64")}"; };
      };
      forAll = f: nixpkgs.lib.genAttrs (builtins.attrNames systems) f;
    in {
      packages = forAll (system:
        let
          pkgs = nixpkgs.legacyPackages.\${system};
          here = systems.\${system};
        in {
          default = pkgs.stdenvNoCC.mkDerivation {
            pname = "perch";
            version = "${number}";
            src = pkgs.fetchurl {
              url = "https://github.com/${repo}/releases/download/${version}/\${here.asset}";
              sha256 = here.sha256;
            };
            dontUnpack = true;
            installPhase = "install -Dm755 $src $out/bin/perch";
          };
        });
    };
}
`;
}

/** Every packaging file for a release, by the path it is written to. */
export function packagingFor(version: string, sums: Sums, repo = REPO): Record<string, string> {
  const files: Record<string, string> = {
    "homebrew/perch.rb": homebrew(version, sums, repo),
    "aur/PKGBUILD": pkgbuild(version, sums, repo),
    "nix/flake.nix": flake(version, sums, repo),
  };
  for (const [name, body] of Object.entries(winget(version, sums, repo))) {
    files[`winget/${name}`] = body;
  }
  return files;
}

if (import.meta.main) {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      version: { type: "string" },
      sums: { type: "string" },
      out: { type: "string" },
      repo: { type: "string" },
    },
  });
  const version = values.version ?? process.env.PERCH_VERSION;
  if (!version) throw new Error("--version is required");
  const sums = parseSums(readFileSync(resolve(values.sums ?? "dist/cli/SHA256SUMS"), "utf8"));
  const out = resolve(values.out ?? "dist/packaging");
  for (const [name, body] of Object.entries(packagingFor(version, sums, values.repo ?? REPO))) {
    const path = join(out, name);
    mkdirSync(join(path, ".."), { recursive: true });
    writeFileSync(path, body);
    console.log(`wrote ${path}`);
  }
}
