#!/usr/bin/env bun
/**
 * Regenerates src/migrations/index.ts from drizzle/meta/_journal.json so every migration's SQL is imported
 * as text and embedded at build time. Runs after `drizzle-kit generate` (`bun run generate`).
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

type Journal = {
  version: string;
  dialect: string;
  entries: Array<{ idx: number; version: string; when: number; tag: string; breakpoints: boolean }>;
};

const root = resolve(import.meta.dir, "..");
const journalPath = join(root, "drizzle", "meta", "_journal.json");
if (!existsSync(journalPath)) {
  console.error(`no journal at ${journalPath}; run drizzle-kit generate first`);
  process.exit(1);
}
const journal = JSON.parse(readFileSync(journalPath, "utf8")) as Journal;
const entries = [...journal.entries].sort((a, b) => a.idx - b.idx);

const imports = entries
  .map((e, i) => `import m${i} from "../../drizzle/${e.tag}.sql" with { type: "text" };`)
  .join("\n");
const sources = entries
  .map(
    (e, i) =>
      `  { idx: ${e.idx}, tag: ${JSON.stringify(e.tag)}, when: ${e.when}, breakpoints: ${e.breakpoints}, sql: m${i} },`,
  )
  .join("\n");

const out = `// Generated by scripts/embed-migrations.ts from drizzle/meta/_journal.json. Do not edit.
${imports}

export type MigrationSource = {
  idx: number;
  tag: string;
  when: number;
  breakpoints: boolean;
  sql: string;
};

export const migrationSources: MigrationSource[] = [
${sources}
];
`;
writeFileSync(join(root, "src", "migrations", "index.ts"), out);
console.log(`embedded ${entries.length} migration(s) into src/migrations/index.ts`);
